export default {
  ride1: {
    state_from: 'Abuja',
    state_to: 'Lagos',
    city_from: 'New York',
    city_to: 'Ajegunle',
    price: 400.03,
    departure_date: '2018-10-11',
    departure_time: '16:11:14',
    pickup_location: 'Anthony Park',
    user_id: 1,
  },
  ride2: {
    state_from: 'Toronto',
    state_to: 'Sokoto',
    city_from: 'Lafia',
    city_to: 'Akwanga',
    price: 750,
    departure_date: '2018-11-11',
    departure_time: '10:16:10',
    pickup_location: 'Oshodi Park',
    user_id: 2,
  },
  ride3: {
    state_from: 'Maritau',
    state_to: 'Parista',
    city_from: 'Sauntol',
    city_to: 'Sevastopol',
    price: 750,
    departure_date: '2018-10-12',
    departure_time: '11:16:10',
    pickup_location: 'Interstar Shuttles',
    user_id: 1,
  },
};

